;;; directory-slideshow-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from directory-slideshow.el

(autoload 'directory-slideshow-start "directory-slideshow" "\
Start the slideshow.
When called interactively, prompt for a DIRECTORY unless in Dired
mode.

(fn &optional DIRECTORY)" t)
(register-definition-prefixes "directory-slideshow" '("directory-slideshow-"))

;;; End of scraped data

(provide 'directory-slideshow-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; directory-slideshow-autoloads.el ends here
