;;; org-graph-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from org-graph.el

(autoload 'org-graph-view "org-graph" "\
Show Org graph." t)
(autoload 'org-graph-refresh "org-graph" "\
Refresh graph." t)
(register-definition-prefixes "org-graph" '("org-graph-"))

;;; End of scraped data

(provide 'org-graph-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-graph-autoloads.el ends here
