;;; calle24-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from calle24.el

 (autoload 'calle24-dark-appearance "calle24" nil t)
 (autoload 'calle24-light-appearance "calle24" nil t)
 (autoload 'calle24-refresh-appearance "calle24" nil t)
 (autoload 'calle24-install "calle24" nil t)
 (autoload 'calle24-uninstall "calle24" nil t)
(register-definition-prefixes "calle24" '("calle24-"))

;;; End of scraped data

(provide 'calle24-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; calle24-autoloads.el ends here
