;;; comint-histories-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from comint-histories.el

(register-definition-prefixes "comint-histories" '("comint-histories-"))

;;; End of scraped data

(provide 'comint-histories-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; comint-histories-autoloads.el ends here
