;;; org-cmenu-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from org-cmenu.el

(register-definition-prefixes "org-cmenu" '("org-cmenu"))


;;; Generated autoloads from org-cmenu-setup.el

(register-definition-prefixes "org-cmenu-setup" '("org-cmenu-setup-reset"))


;;; Generated autoloads from org-cmenu-tools.el

(register-definition-prefixes "org-cmenu-tools" '("org-cmenu-"))


;;; Generated autoloads from org-cmenu-typedoc.el

(register-definition-prefixes "org-cmenu-typedoc" '("org-cmenu-"))

;;; End of scraped data

(provide 'org-cmenu-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-cmenu-autoloads.el ends here
