;;; org-transclusion-blocks-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from org-transclusion-blocks.el

(autoload 'org-transclusion-blocks-convert-keyword-at-point "org-transclusion-blocks" "\
Convert #+transclude: keyword at point to header block form.

Parses the keyword line using `org-transclusion-keyword-string-to-plist',
extracts :link, :lines, :thing-at-point, and residual keywords,
then generates equivalent header form:

  ,#+HEADER: :transclude LINK
  ,#+HEADER: :transclude-lines RANGE   ; if :lines present
  ,#+HEADER: :transclude-thing THING   ; if :thing-at-point present
  ,#+HEADER: :transclude-keywords RESIDUAL  ; if other keywords remain
  ,#+begin_src LANG
  ,#+end_src

Original keyword line is commented for reference.

Block language defaults to `elisp'.  Customize with prefix argument:
with \\[universal-argument], prompt for block type.

Point must be on #+transclude: keyword line.

Returns t on success, nil if not on keyword line.

See Info node `(org-transclusion-blocks) Converting Keywords'." t)
(autoload 'org-transclusion-blocks-convert-keywords-in-region "org-transclusion-blocks" "\
Convert all #+transclude: keywords to header form in region.

BEG and END delimit region to process.

Converts each #+transclude: keyword line within region using
`org-transclusion-blocks-convert-keyword-at-point'.

Returns list of positions where conversions occurred.

Interactively, operates on active region if present, otherwise
prompts for region boundaries.

See Info node `(org-transclusion-blocks) Batch Converting'.

(fn BEG END)" t)
(autoload 'org-transclusion-blocks-convert-keywords-in-buffer "org-transclusion-blocks" "\
Convert all #+transclude: keywords to header form in buffer.

Delegates to `org-transclusion-blocks-convert-keywords-in-region'
with buffer bounds.

Returns list of positions where conversions occurred." t)
(autoload 'org-transclusion-blocks-add "org-transclusion-blocks" "\
Fetch and insert transcluded content into block at point.

Supports two mutually exclusive header forms:

1. Direct link mode:
   #+HEADER: :transclude [[TYPE:PATH::SEARCH]]
   #+HEADER: :transclude-keywords \":level 2\"  ; optional

2. Component mode (requires registered type):
   #+HEADER: :transclude-type REGISTERED-TYPE
   #+HEADER: :TYPE-COMPONENT-1 VALUE
   #+HEADER: :TYPE-COMPONENT-2 VALUE

Point must be on or within a supported block type.

For src-blocks, uses Babel for header processing.
For other blocks, parses headers directly.

Runs validators via `org-transclusion-blocks--pre-validate-headers' when
typed components detected.

Applies Org syntax escaping via
`org-transclusion-blocks--escape-org-syntax' when
`org-transclusion-blocks--should-escape-p' returns non-nil.

Stores metadata in text properties for boundary checking:
- `org-transclusion-blocks-keyword' - keyword plist
- `org-transclusion-blocks-link' - constructed link
- `org-transclusion-blocks-max-line' - source line count

See `org-transclusion-blocks-list-types' for available types.

Returns t on success, nil if no headers or fetch failed." t)
(autoload 'org-transclusion-blocks-add-all "org-transclusion-blocks" "\
Fetch and insert content for all blocks in SCOPE.

SCOPE can be:
  nil or \\='buffer - entire buffer (default)
  \\='subtree       - current subtree
  \\='region        - active region

Processes all supported block types with transclusion headers.

Returns list of successfully processed block positions.

(fn &optional SCOPE)" t)
(autoload 'org-transclusion-blocks-validate-current-block "org-transclusion-blocks" "\
Validate current block without inserting content.

Tests validator configurations without content fetching overhead.

Runs `org-transclusion-blocks--pre-validate-headers' when typed components
detected.

Useful for testing validator configurations during development." t)
(autoload 'org-transclusion-blocks-describe-type "org-transclusion-blocks" "\
Display comprehensive documentation for TYPE.

TYPE is symbol naming registered link type.

Shows:
- Component specifications
- Validators for each component
- Interaction constraints (required, shadowed-by, requires, conflicts)
- Constructor function
- Usage example

See `org-transclusion-blocks-list-types' for available types.

(fn TYPE)" t)
(autoload 'org-transclusion-blocks-list-types "org-transclusion-blocks" "\
Show all registered types with component counts.

Displays table of registered link types from
`org-transclusion-blocks--type-components'.

Use `org-transclusion-blocks-describe-type' for detailed information about
specific types." t)
(register-definition-prefixes "org-transclusion-blocks" '("org-transclusion-blocks-"))


;;; Generated autoloads from org-transclusion-blocks-lines.el

(autoload 'org-transclusion-blocks-set-lines "org-transclusion-blocks-lines" "\
Set line range to START-END.

START and END are line numbers. Enter empty string for open-ended.

Examples:
  10 20  → :lines 10-20
  10 \"\"  → :lines 10-
  \"\" 20  → :lines -20

(fn START END)" t)
(autoload 'org-transclusion-blocks-set-lines-range "org-transclusion-blocks-lines" "\
Set line range with WIDTH centered on current range.

WIDTH is number of lines to include.

If current range is 10-20, setting WIDTH to 5 produces 13-17
(centered on midpoint 15).

(fn WIDTH)" t)
(autoload 'org-transclusion-blocks-expand-lines-range "org-transclusion-blocks-lines" "\
Expand line range by AMOUNT lines on both ends.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves start earlier and end later.

If range is 10-20, expanding by 2 produces 8-22.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-shrink-lines-range "org-transclusion-blocks-lines" "\
Shrink line range by AMOUNT lines on both ends.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves start later and end earlier.

If range is 10-20, shrinking by 2 produces 12-18.
Errors if range becomes invalid (start > end).

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-scroll-down "org-transclusion-blocks-lines" "\
Scroll line range down by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves both start and end later.

If range is 10-20, scrolling down by 3 produces 13-23.

Prevented when end already at source maximum line.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-scroll-up "org-transclusion-blocks-lines" "\
Scroll line range up by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves both start and end earlier.

If range is 10-20, scrolling up by 3 produces 7-17.
Start cannot go below 1.

Prevented when start already at line 1.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-expand-up "org-transclusion-blocks-lines" "\
Expand range upward by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves start earlier, end unchanged.

Example:
  Before: 50-100
  After (amount=20): 30-100

Prevented when start already at line 1.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-expand-down "org-transclusion-blocks-lines" "\
Expand range downward by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves end later, start unchanged.

Example:
  Before: 50-100
  After (amount=20): 50-120

Prevented when end already at source maximum line.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-shrink-up "org-transclusion-blocks-lines" "\
Shrink range from top by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves start later, end unchanged.

Example:
  Before: 50-100
  After (amount=10): 60-100

Errors if start would exceed end.

(fn AMOUNT)" t)
(autoload 'org-transclusion-blocks-shrink-down "org-transclusion-blocks-lines" "\
Shrink range from bottom by AMOUNT lines.

AMOUNT defaults to `org-transclusion-blocks-lines-default-increment'.
Moves end earlier, start unchanged.

Example:
  Before: 50-100
  After (amount=10): 50-90

Errors if end would go below start.

(fn AMOUNT)" t)
(register-definition-prefixes "org-transclusion-blocks-lines" '("org-transclusion-blocks-lines-"))

;;; End of scraped data

(provide 'org-transclusion-blocks-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-transclusion-blocks-autoloads.el ends here
