;;; theme-switcher-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from theme-switcher.el

(register-definition-prefixes "theme-switcher" '("*theme-switcher-themes-" "insert-dark-before-extension" "lookup" "theme-switcher-choose-theme" "ts-"))

;;; End of scraped data

(provide 'theme-switcher-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-switcher-autoloads.el ends here
