;;; stripspace-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from stripspace.el

(autoload 'stripspace-cleanup "stripspace" "\
Delete trailing whitespace in the current buffer or region." t)
(autoload 'stripspace-local-mode "stripspace" "\
Toggle `stripspace-local-mode'.

This mode ensures that trailing whitespace is removed before saving a buffer.

This is a minor mode.  If called interactively, toggle the
`Stripspace-Local mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `stripspace-local-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "stripspace" '("stripspace-"))

;;; End of scraped data

(provide 'stripspace-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stripspace-autoloads.el ends here
