;;; theme-switcher-consult-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from theme-switcher-consult.el

(register-definition-prefixes "theme-switcher-consult" '("theme-switcher-consult-"))

;;; End of scraped data

(provide 'theme-switcher-consult-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-switcher-consult-autoloads.el ends here
