;;; scratch-comment-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from scratch-comment.el

(autoload 'scratch-comment-eval-sexp "scratch-comment" "\
Eval sexp before point and print result as comment.
see `eval-print-last-sexp'." t)
(register-definition-prefixes "scratch-comment" '("scratch-comment-"))

;;; End of scraped data

(provide 'scratch-comment-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; scratch-comment-autoloads.el ends here
