;;; denote-dired-weblinks-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from denote-dired-weblinks.el

(autoload 'denote-dired-weblinks-create-bookmark "denote-dired-weblinks" "\
Create a new Denote bookmark file for URL with TITLE.
Optional KEYWORDS are additional Denote keywords besides the
bookmark keyword.

See `denote' command documentation for information about
FILE-TYPE, DIRECTORY, DATE, TEMPLATE and SIGNATURE.

(fn &optional URL TITLE KEYWORDS FILE-TYPE DIRECTORY DATE TEMPLATE SIGNATURE)" t)
(autoload 'denote-dired-weblinks-mode "denote-dired-weblinks" "\
Minor mode to open Denote bookmark files as URLs in Dired.

This is a minor mode.  If called interactively, toggle the
`Denote-Dired-Weblinks mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `denote-dired-weblinks-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "denote-dired-weblinks" '("denote-dired-weblinks-"))

;;; End of scraped data

(provide 'denote-dired-weblinks-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; denote-dired-weblinks-autoloads.el ends here
