;;; archiver-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from archiver.el

(autoload 'archiver-archive-heading "archiver" "\
Write the current Org subtree to the archive file.
Merge it with the existing tree." t)
(autoload 'archiver-archive-open-file "archiver" "\
Move the current file to the archive directory." t)
(register-definition-prefixes "archiver" '("*archiver-agenda-archive-location*" "archiver-" "buffer-has-only-whitespace-before-first-heading-p" "get-archive-location" "my-archive-dir" "replace-file-contents-and-restore-points" "tree"))

;;; End of scraped data

(provide 'archiver-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; archiver-autoloads.el ends here
